### ISSUE TITLE
Discussione articolo 3

### ISSUE THREAD

**Issue by g5pw** [mittelab/statuto#1]
Inizio io: Mittelab in questo caso è un'associazione, non un luogo fisico... Possiamo mettere qualcosa tipo

> L'associazione si prefigge di gestire un hackerspace di matrice nordeuropea, un luogo fisico ecc. ecc.

Questo vuol dire che l'associazione Mittelab *deve* gestire un hackerspace. No hackerspace, no mittelab, il che secondo me ha senso. Che ne dite?

**Comment by tlxyz** [comment]
Direi che più che aver senso è corretto:
Un'associazione non è un posto ma un gruppo di persone con un interesse comune

**Comment by g5pw** [comment]
Esatto. Come potremmo meglio esprimere questo?

**Comment by tlxyz** [comment]
Sarebbe da definire  "hackerspace di matrice nord europea"

**Comment by g5pw** [comment]
Secondo me una definizione potrebbe essere:

> posto fisico dove appassionati di elettronica, informatica e tecnologia si incontrano per collaborare e condividere idee, equipaggiamento e conoscenze.
