### ISSUE TITLE
Possibile problema nello statuto

### ISSUE THREAD

**Issue by g5pw** [mittelab/statuto#4]
Seguento le regole specificate [qui](http://www.teamartist.com/blog/2012/04/18/il-vostro-statuto-e-in-regola-per-poter-godere-del-regime-fiscale-agevolato/), a quanto pare a noi manca il punto 3 nello statuto. Però ci crea un problemino: Nico e Giulio sono nel LUG!

**Comment by tlxyz** [comment]
Aprofondisco,Da qurl che so non si possono ricoprire le stesse carico,IndagoGiulioInviato da dispositivo Honor-------- Messaggio originale --------Oggetto: [statuto] Possibile problema nello statuto (#4)Da: Aljaž Srebrnič A: mittelab/statuto CC: A quanto dicono qui, a quanto pare a noi manca il punto 3 nello statuto. Però ci crea un problemino: Nico e Giulio sono nel LUG!

**Comment by g5pw** [comment]
@tlxyz trovato qualcosa di interessante? l'altro giorno avevo visto che valeva solo per le ASD.
